window.quizBanks = window.quizBanks || {};
window.quizBanks.elc2 = {
  id: "elc2",
  title: "ELC2 — Thyroid, adrenal, calcium and diabetes",
  shortTitle: "ELC2",
  description: "Thyroid disease, adrenal disorders, calcium/PTH interpretation, insulin physiology and diabetes in pregnancy.",
  blueprintBatch: "Batch B",
  questions: [
    {
      id: "thyroid-synthesis-tpo-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Thyroid hormone synthesis",
      moduleLOs: ["LO1"],
      sessionLOs: ["Describe the synthesis of thyroid hormones T4 and T3, where this takes place and how they are transported in blood"],
      disciplines: ["physiology"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "thyroid-synthesis",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review thyroid hormone synthesis: iodide trapping, TPO-mediated organification onto thyroglobulin and release of mainly T4 with some T3.",
      question: "A patient is prescribed an antithyroid drug that reduces new thyroid hormone synthesis by inhibiting thyroid peroxidase.",
      leadIn: "Which step is most directly inhibited?",
      options: ["Organification of iodide onto thyroglobulin", "Peripheral conversion of T4 to T3 only", "Release of TRH from the hypothalamus", "Binding of T3 to albumin in plasma", "Calcitonin secretion by C cells"],
      answer: 0,
      explanation: "Thyroid peroxidase organifies iodide onto thyroglobulin and couples iodotyrosines to make T4 and T3."
    },
    {
      id: "thyroid-tbg-pregnancy-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Plasma protein binding and free thyroid hormone",
      moduleLOs: ["LO1"],
      sessionLOs: ["Describe the role of plasma protein binding in the actions of some hormones"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "thyroid-binding-protein",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review that pregnancy raises thyroid-binding globulin, increasing total T4 while free T4 remains the biologically relevant measurement.",
      question: "A pregnant patient has raised total T4 but normal free T4 and normal TSH.",
      leadIn: "Which explanation best accounts for this result?",
      options: ["Increased thyroid-binding globulin", "Primary hyperthyroidism", "Secondary hypothyroidism", "Autoimmune destruction of the thyroid", "Radioactive iodine exposure"],
      answer: 0,
      explanation: "Pregnancy increases thyroid-binding globulin, raising total thyroid hormone. The free fraction is biologically active and may remain normal."
    },
    {
      id: "thyroid-t4-prohormone-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "T4 as prohormone and T3 as active hormone",
      moduleLOs: ["LO1"],
      sessionLOs: ["Recall that T4 is a prohormone and T3 is the active thyroid hormone following peripheral deiodinase action"],
      disciplines: ["physiology"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "thyroid-prohormone",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review T4 as the main secreted prohormone, converted peripherally to active T3 by deiodinase.",
      question: "Most thyroid hormone secreted by the thyroid gland is T4, but many target tissue effects are mediated by T3.",
      leadIn: "Which process explains this?",
      options: ["Peripheral deiodination of T4", "Conversion of TSH into T3", "Direct secretion of T3 by the posterior pituitary", "Binding of calcitonin to TBG", "Renal activation of prolactin"],
      answer: 0,
      explanation: "T4 is converted in peripheral tissues to active T3 by deiodinase enzymes."
    },
    {
      id: "thyroid-primary-hyperthyroid-tfts-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Primary hyperthyroidism TFT pattern",
      moduleLOs: ["LO1", "LO4"],
      sessionLOs: ["Describe the role of TRH and TSH in regulation of thyroid function", "Describe causes, signs, symptoms and treatment of hyperthyroidism"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "thyroid-axis-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review thyroid axis logic: primary hyperthyroidism gives high free T4/T3 with suppressed TSH because of negative feedback.",
      question: "A patient has weight loss, tremor, palpitations and heat intolerance. Blood tests show high free T4 and suppressed TSH.",
      leadIn: "Which interpretation best fits these results?",
      options: ["Primary hyperthyroidism", "Primary hypothyroidism", "Secondary hypothyroidism", "Hypopituitarism with low thyroid output", "Normal pregnancy-related TBG rise only"],
      answer: 0,
      explanation: "High free T4 with suppressed TSH indicates primary hyperthyroidism, as thyroid hormone suppresses pituitary TSH."
    },
    {
      id: "thyroid-primary-hypothyroid-tfts-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Primary hypothyroidism TFT pattern",
      moduleLOs: ["LO1", "LO4"],
      sessionLOs: ["Describe causes, signs, symptoms and treatment of hypothyroidism"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "axis-logic",
      variantType: "thyroid-axis-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review primary hypothyroidism as low free T4 with high TSH because the thyroid gland is failing and pituitary stimulation rises.",
      question: "A patient has fatigue, weight gain and cold intolerance. Blood tests show low free T4 and high TSH.",
      leadIn: "Which level of the thyroid axis is most likely failing?",
      options: ["Thyroid gland", "Pituitary gland", "Hypothalamus", "Thyroid-binding globulin", "Posterior pituitary"],
      answer: 0,
      explanation: "Low free T4 with raised TSH indicates primary thyroid failure. The pituitary increases TSH because thyroid hormone feedback is reduced."
    },
    {
      id: "thyroid-secondary-hypothyroid-tfts-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Secondary hypothyroidism TFT pattern",
      moduleLOs: ["LO1", "LO4"],
      sessionLOs: ["Identify primary and secondary causes of abnormal hormone secretion"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "axis-logic",
      variantType: "thyroid-axis-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review secondary hypothyroidism as low free T4 with low or inappropriately normal TSH from pituitary failure.",
      question: "A patient with a pituitary mass has fatigue and cold intolerance. Blood tests show low free T4 with low TSH.",
      leadIn: "Which diagnosis best explains this pattern?",
      options: ["Secondary hypothyroidism", "Primary hypothyroidism", "Graves' disease", "Hashimoto thyroiditis with intact pituitary response", "TBG excess with normal free hormone"],
      answer: 0,
      explanation: "Pituitary failure can cause low TSH and therefore low thyroid hormone, producing secondary hypothyroidism."
    },
    {
      id: "thyroid-graves-pregnancy-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Hyperthyroidism management in pregnancy",
      moduleLOs: ["LO4", "LO7", "LO9"],
      sessionLOs: ["Describe the causes, signs, symptoms and treatment of the common diseases causing hyper and hypothyroidism before and after birth"],
      disciplines: ["pathology", "pharmacology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "management",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review Graves' disease treatment choices, especially PTU in the first trimester and radioactive iodine contraindication in pregnancy.",
      question: "A 27-year-old woman who is 9 weeks pregnant has weight loss, tremor and palpitations. Blood tests show suppressed TSH and raised free T4. Graves' disease is suspected.",
      leadIn: "Which treatment is the most appropriate antithyroid drug in the first trimester?",
      options: ["Propylthiouracil", "Carbimazole", "Radioactive iodine", "Levothyroxine", "Desmopressin"],
      answer: 0,
      explanation: "Propylthiouracil is preferred in the first trimester. Carbimazole is usually avoided early in pregnancy, and radioactive iodine is contraindicated."
    },
    {
      id: "thyroid-carbimazole-agranulocytosis-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Carbimazole adverse effect counselling",
      moduleLOs: ["LO7"],
      sessionLOs: ["Describe treatment of common diseases causing hyperthyroidism"],
      disciplines: ["pharmacology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "thyroid-drug-counselling",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review carbimazole counselling: sore throat or fever may indicate agranulocytosis, so stop the drug and check FBC urgently.",
      question: "A patient taking carbimazole for Graves' disease develops fever and a sore throat.",
      leadIn: "Which action is most appropriate?",
      options: ["Stop carbimazole and arrange urgent full blood count", "Double the carbimazole dose", "Reassure this is expected and harmless", "Start radioactive iodine immediately in pregnancy", "Treat with levothyroxine without checking blood count"],
      answer: 0,
      explanation: "Carbimazole can cause agranulocytosis. Fever or sore throat requires stopping the drug and urgent FBC."
    },
    {
      id: "thyroid-hashimoto-mechanism-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Graves versus Hashimoto immunology",
      moduleLOs: ["LO4"],
      sessionLOs: ["Recognise clinical and causative immunological differences between major autoimmune thyroid diseases"],
      disciplines: ["immunology", "pathology", "clinical aspects"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "thyroid-autoimmunity",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review Graves as TRAb stimulation causing hyperthyroidism and Hashimoto as anti-TPO/anti-thyroglobulin destructive thyroiditis causing hypothyroidism.",
      question: "A patient has progressive hypothyroidism with positive anti-TPO antibodies.",
      leadIn: "Which mechanism best explains the condition?",
      options: ["Autoimmune destruction of thyroid tissue", "TSH receptor stimulation by TRAb", "Pituitary ACTH excess", "Iodide trapping by posterior pituitary", "Ectopic ADH production"],
      answer: 0,
      explanation: "Hashimoto thyroiditis is associated with anti-TPO and anti-thyroglobulin antibodies and causes destructive thyroiditis leading to hypothyroidism."
    },
    {
      id: "thyroid-eye-disease-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid",
      component: "Thyroid eye disease clinical picture",
      moduleLOs: ["LO4"],
      sessionLOs: ["Describe and understand the clinical picture found in thyroid eye disease"],
      disciplines: ["immunology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "thyroid-eye-disease",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review thyroid eye disease as Graves-specific orbital fibroblast inflammation causing proptosis, lid signs, diplopia and potential optic nerve compression; smoking worsens it.",
      question: "A patient with Graves' disease has proptosis, lid retraction and diplopia. They smoke heavily.",
      leadIn: "Which process best explains these eye signs?",
      options: ["Autoimmune inflammation of retro-orbital tissue", "Retinal detachment caused by levothyroxine", "Cataract formation due to iodine deficiency", "Bacterial infection of the lacrimal duct", "Posterior pituitary hormone excess"],
      answer: 0,
      explanation: "Thyroid eye disease is Graves-related autoimmune inflammation of retro-orbital tissues, worsened by smoking."
    },
    {
      id: "thyroid-rln-surgery-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Thyroid anatomy",
      component: "Recurrent laryngeal nerve injury in thyroid surgery",
      moduleLOs: ["LO1", "LO10"],
      sessionLOs: ["Apply gross anatomical knowledge to clinical correlations"],
      disciplines: ["anatomy", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "anatomical-localisation",
      variantType: "thyroid-surgical-risk",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review the recurrent laryngeal nerve running behind the thyroid in the tracheo-oesophageal groove and causing hoarseness if injured during thyroidectomy.",
      question: "A patient has a hoarse voice after thyroidectomy. Laryngoscopy shows unilateral vocal cord palsy.",
      leadIn: "Which structure was most likely injured?",
      options: ["Recurrent laryngeal nerve", "Optic chiasm", "Pudendal nerve", "Adrenal medulla", "Parathyroid hormone receptor"],
      answer: 0,
      explanation: "The recurrent laryngeal nerve is at risk during thyroidectomy and injury causes vocal cord palsy and hoarseness."
    },
    {
      id: "adrenal-zones-output-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Adrenal cortex zones and hormone output",
      moduleLOs: ["LO1"],
      sessionLOs: ["Describe how the anatomy of the adrenal gland determines its output"],
      disciplines: ["anatomy", "physiology"],
      cognitiveLevel: "remember",
      assessmentSkill: "mechanism",
      variantType: "adrenal-zone-output",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review adrenal cortex zones: glomerulosa makes aldosterone, fasciculata makes cortisol, reticularis makes androgens; medulla makes catecholamines.",
      question: "A histology image labels the zona glomerulosa of the adrenal cortex.",
      leadIn: "Which hormone is mainly produced by this zone?",
      options: ["Aldosterone", "Cortisol", "DHEA", "Adrenaline", "Thyroxine"],
      answer: 0,
      explanation: "The zona glomerulosa produces aldosterone. The fasciculata produces cortisol and the reticularis produces adrenal androgens."
    },
    {
      id: "adrenal-cortisol-effects-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Cortisol regulation and effects",
      moduleLOs: ["LO1"],
      sessionLOs: ["Describe hormones secreted by the adrenal cortex, their regulation and effects"],
      disciplines: ["physiology"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "cortisol-physiology",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review cortisol as ACTH-driven with effects including gluconeogenesis, protein catabolism, anti-inflammatory action and maintaining vascular tone.",
      question: "A patient with adrenal insufficiency becomes hypotensive during severe infection because they cannot mount an adequate cortisol response.",
      leadIn: "Which physiological role of cortisol is most relevant?",
      options: ["Maintenance of vascular tone", "Direct secretion of insulin", "Lowering blood glucose by GLUT4 insertion", "Suppressing aldosterone through renin", "Producing thyroid hormone"],
      answer: 0,
      explanation: "Cortisol supports vascular tone and stress responses. Deficiency can contribute to hypotension during illness."
    },
    {
      id: "adrenal-cushing-features-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Cushing syndrome clinical recognition",
      moduleLOs: ["LO4", "LO7"],
      sessionLOs: ["Describe causes, clinical manifestations and treatment of ACTH excess and Cushing's syndrome"],
      disciplines: ["pathology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "cushing-recognition",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review Cushing syndrome features: central obesity, moon face, buffalo hump, purple striae, easy bruising, proximal myopathy, diabetes, hypertension and mood change.",
      question: "A patient has central weight gain, proximal muscle weakness, purple abdominal striae, hypertension and new diabetes.",
      leadIn: "Which endocrine disorder is most likely?",
      options: ["Cushing syndrome", "Diabetes insipidus", "Primary hypoparathyroidism", "Nephrogenic SIADH", "Hashimoto thyroiditis"],
      answer: 0,
      explanation: "These are typical features of cortisol excess in Cushing syndrome."
    },
    {
      id: "adrenal-addison-primary-secondary-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Primary versus secondary adrenal insufficiency",
      moduleLOs: ["LO4", "LO13"],
      sessionLOs: ["Explain the significance of disorders of adrenal function in adulthood"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "adrenal-axis-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review primary adrenal insufficiency as low cortisol with high ACTH and hyperpigmentation/aldosterone loss; secondary adrenal insufficiency has low ACTH and preserved aldosterone.",
      question: "A patient has fatigue, weight loss, postural dizziness, hyperpigmentation, hyponatraemia and hyperkalaemia. Cortisol is low and ACTH is high.",
      leadIn: "Which diagnosis best fits this pattern?",
      options: ["Primary adrenal insufficiency", "Secondary adrenal insufficiency", "Cushing disease", "Conn syndrome", "Phaeochromocytoma"],
      answer: 0,
      explanation: "High ACTH with low cortisol indicates primary adrenal failure. Hyperpigmentation and hyperkalaemia support primary adrenal insufficiency with mineralocorticoid loss."
    },
    {
      id: "adrenal-conn-pattern-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Conn syndrome biochemical pattern",
      moduleLOs: ["LO4", "LO5", "LO7"],
      sessionLOs: ["Understand secondary endocrine causes of hypertension"],
      disciplines: ["physiology", "pathology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "endocrine-hypertension",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review Conn syndrome: resistant hypertension, hypokalaemia, metabolic alkalosis, high aldosterone and suppressed renin.",
      question: "A young patient has resistant hypertension, muscle weakness and low potassium. Blood tests show high aldosterone and suppressed renin.",
      leadIn: "Which diagnosis is most likely?",
      options: ["Primary hyperaldosteronism", "Phaeochromocytoma", "Addison disease", "Secondary hypothyroidism", "SIADH"],
      answer: 0,
      explanation: "High aldosterone with suppressed renin, hypertension and hypokalaemia is typical of primary hyperaldosteronism/Conn syndrome."
    },
    {
      id: "adrenal-phaeo-alpha-before-beta-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Phaeochromocytoma management safety",
      moduleLOs: ["LO4", "LO7"],
      sessionLOs: ["Understand endocrine causes of hypertension and their management"],
      disciplines: ["pathology", "pharmacology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "phaeochromocytoma-management",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review phaeochromocytoma management: alpha blockade first, then beta blockade; beta blockade first can cause hypertensive crisis.",
      question: "A patient has episodic headache, palpitations, sweating and paroxysmal hypertension. Phaeochromocytoma is diagnosed before planned surgery.",
      leadIn: "Which pre-operative drug sequence is safest?",
      options: ["Alpha blockade before beta blockade", "Beta blockade before alpha blockade", "Levothyroxine before carbimazole", "Desmopressin before fluid restriction", "Insulin before glucose monitoring"],
      answer: 0,
      explanation: "Alpha blockade must precede beta blockade in phaeochromocytoma to avoid unopposed alpha vasoconstriction and hypertensive crisis."
    },
    {
      id: "adrenal-cah-21hydroxylase-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Adrenal",
      component: "Congenital adrenal hyperplasia",
      moduleLOs: ["LO1", "LO4"],
      sessionLOs: ["Explain the significance of disorders of adrenal function in fetal life"],
      disciplines: ["physiology", "pathology", "embryology"],
      cognitiveLevel: "apply",
      assessmentSkill: "mechanism",
      variantType: "cah-pathway",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review 21-hydroxylase deficiency: impaired cortisol/aldosterone synthesis, raised ACTH and androgen shunt causing virilisation and possible salt-wasting crisis.",
      question: "A newborn has ambiguous external genitalia and later develops vomiting, dehydration and hyponatraemia. 21-hydroxylase deficiency is suspected.",
      leadIn: "Which mechanism best explains the virilisation?",
      options: ["ACTH-driven androgen excess", "Excess fetal cortisol", "Reduced testosterone conversion to DHT only", "High maternal iodine intake", "Peripheral T4 to T3 conversion"],
      answer: 0,
      explanation: "21-hydroxylase deficiency impairs cortisol and aldosterone synthesis. ACTH rises and steroid precursors are diverted into androgen production."
    },
    {
      id: "calcium-pth-interpretation-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Calcium",
      component: "Paired calcium and PTH interpretation",
      moduleLOs: ["LO4", "LO5"],
      sessionLOs: ["Have a clear diagnostic and workup plan for calcium disorders", "Understand the most common causes of calcium disorders"],
      disciplines: ["physiology", "pathology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "biochemistry-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review the paired calcium and PTH framework: high calcium plus suppressed PTH points away from primary hyperparathyroidism and towards malignancy or another PTH-independent cause.",
      question: "A patient has confusion, constipation and bone pain. Blood tests show raised adjusted calcium and suppressed PTH.",
      leadIn: "Which cause is most consistent with these results?",
      options: ["Malignancy-associated hypercalcaemia", "Primary hyperparathyroidism", "Post-thyroidectomy hypoparathyroidism", "Vitamin D deficiency", "Chronic kidney disease causing secondary hyperparathyroidism"],
      answer: 0,
      explanation: "High calcium with suppressed PTH suggests a PTH-independent cause such as malignancy-associated hypercalcaemia. Primary hyperparathyroidism would have inappropriately normal or high PTH."
    },
    {
      id: "calcium-primary-hpt-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Calcium",
      component: "Primary hyperparathyroidism pattern",
      moduleLOs: ["LO4", "LO5"],
      sessionLOs: ["Have a clear diagnostic and workup plan for calcium disorders"],
      disciplines: ["physiology", "pathology", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "calcium-pth-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review primary hyperparathyroidism as high calcium with inappropriately normal or high PTH.",
      question: "A patient has renal stones and constipation. Blood tests show raised calcium with an inappropriately high PTH.",
      leadIn: "Which diagnosis is most likely?",
      options: ["Primary hyperparathyroidism", "Malignancy-associated hypercalcaemia", "Hypoparathyroidism", "Vitamin D deficiency with low calcium", "SIADH"],
      answer: 0,
      explanation: "High calcium with high or inappropriately normal PTH indicates primary hyperparathyroidism."
    },
    {
      id: "calcium-vitd-deficiency-pattern-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Calcium",
      component: "Low calcium with raised PTH pattern",
      moduleLOs: ["LO4", "LO5"],
      sessionLOs: ["Understand the most common causes of calcium disorders"],
      disciplines: ["physiology", "pathology"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "calcium-pth-pattern",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review low calcium with raised PTH as a secondary hyperparathyroid response, commonly due to vitamin D deficiency or CKD.",
      question: "A patient has low adjusted calcium and raised PTH. Vitamin D is very low.",
      leadIn: "Which interpretation best fits this pattern?",
      options: ["Secondary hyperparathyroidism due to vitamin D deficiency", "Primary hyperparathyroidism", "Malignancy-associated hypercalcaemia", "Post-thyroidectomy hypoparathyroidism", "Phaeochromocytoma"],
      answer: 0,
      explanation: "Low calcium stimulates PTH secretion. Vitamin D deficiency can cause secondary hyperparathyroidism with low calcium and high PTH."
    },
    {
      id: "calcium-hypocalcaemia-signs-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Calcium",
      component: "Hypocalcaemia clinical signs",
      moduleLOs: ["LO4"],
      sessionLOs: ["Be aware of clinical signs and symptoms of calcium disorders"],
      disciplines: ["clinical aspects", "physiology"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "hypocalcaemia-features",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review hypocalcaemia features: perioral paraesthesia, cramps, tetany, seizures, Chvostek sign and Trousseau sign.",
      question: "A patient develops perioral tingling, carpopedal spasm and a positive Trousseau sign after thyroid surgery.",
      leadIn: "Which electrolyte abnormality is most likely?",
      options: ["Hypocalcaemia", "Hypercalcaemia", "Hyperkalaemia from Addison disease", "Hyponatraemia from SIADH", "Hypoglycaemia after birth"],
      answer: 0,
      explanation: "Post-thyroidectomy hypocalcaemia can occur from parathyroid damage. Features include paraesthesia, tetany and Trousseau sign."
    },
    {
      id: "calcium-acute-hypercalcaemia-treatment-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Calcium",
      component: "Acute hypercalcaemia management",
      moduleLOs: ["LO7"],
      sessionLOs: ["Understand management of calcium disorders"],
      disciplines: ["pharmacology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "calcium-management",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review acute hypercalcaemia treatment with IV saline and bisphosphonate, alongside treatment of the underlying cause.",
      question: "A patient has severe symptomatic hypercalcaemia from malignancy.",
      leadIn: "Which initial management is most appropriate?",
      options: ["Intravenous saline and bisphosphonate", "Fluid restriction only", "Desmopressin", "Carbimazole", "Cabergoline"],
      answer: 0,
      explanation: "Acute severe hypercalcaemia is treated with IV saline and bisphosphonate while investigating and treating the cause."
    },
    {
      id: "insulin-tissue-actions-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Insulin and metabolism",
      component: "Insulin actions by tissue",
      moduleLOs: ["LO1"],
      sessionLOs: ["Determine the actions of insulin in liver, muscle and adipose tissue"],
      disciplines: ["physiology"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "insulin-actions",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review insulin as anabolic: liver glycogenesis and reduced glucose output, muscle GLUT4-mediated uptake and adipose lipogenesis/anti-lipolysis.",
      question: "After a carbohydrate-rich meal, insulin rises.",
      leadIn: "Which effect is expected in skeletal muscle?",
      options: ["Increased GLUT4-mediated glucose uptake", "Increased hepatic gluconeogenesis", "Reduced glycogen synthesis", "Increased adipose lipolysis", "Increased ketogenesis"],
      answer: 0,
      explanation: "Insulin promotes GLUT4-mediated glucose uptake in skeletal muscle and favours storage rather than catabolism."
    },
    {
      id: "fed-fasted-starved-states-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Insulin and metabolism",
      component: "Fed and fasted metabolic states",
      moduleLOs: ["LO1"],
      sessionLOs: ["Understand insulin and blood glucose homeostasis"],
      disciplines: ["physiology"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "metabolic-state",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review metabolic state transitions: insulin dominates fed state, glucagon fasting, and prolonged starvation increases ketogenesis.",
      question: "A person has been fasting for several days. Insulin is low, glucagon is high and ketone production has increased.",
      leadIn: "Which metabolic state is best represented?",
      options: ["Prolonged starvation", "Immediately post-prandial state", "Insulin-dominant storage state", "Primary hyperparathyroidism", "SIADH"],
      answer: 0,
      explanation: "Prolonged fasting/starvation lowers insulin, raises counter-regulatory hormones and increases ketogenesis."
    },
    {
      id: "gdm-ogtt-diagnosis-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Diabetes in pregnancy",
      component: "Gestational diabetes screening and diagnosis",
      moduleLOs: ["LO5", "LO7", "LO9"],
      sessionLOs: ["Diabetes in pregnancy and screening"],
      disciplines: ["endocrinology", "obstetrics", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "public-health-screening",
      variantType: "gdm-screening",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review GDM screening with oral glucose tolerance testing in at-risk patients and the future T2DM risk after GDM.",
      question: "A pregnant patient with risk factors for gestational diabetes is offered diagnostic testing at 24–28 weeks.",
      leadIn: "Which test is most appropriate?",
      options: ["Oral glucose tolerance test", "Dexamethasone suppression test", "Short Synacthen test", "Serum CA-125", "Urine metanephrines"],
      answer: 0,
      explanation: "An oral glucose tolerance test is used to diagnose gestational diabetes in at-risk pregnancy."
    },
    {
      id: "gdm-future-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Diabetes in pregnancy",
      component: "Pregnancy as stress test and future diabetes risk",
      moduleLOs: ["LO2", "LO8", "LO9"],
      sessionLOs: ["Explain the concept of pregnancy as a stress test for future health"],
      disciplines: ["endocrinology", "public health", "clinical aspects"],
      cognitiveLevel: "understand",
      assessmentSkill: "integration",
      variantType: "future-health-risk",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review gestational diabetes as a pregnancy stress-test outcome that predicts increased future type 2 diabetes risk.",
      question: "A patient had gestational diabetes and asks why she needs long-term follow-up after delivery.",
      leadIn: "Which future health risk is increased?",
      options: ["Type 2 diabetes", "Congenital adrenal hyperplasia", "Thyroid eye disease", "Cervical intraepithelial neoplasia", "Phaeochromocytoma"],
      answer: 0,
      explanation: "Gestational diabetes indicates increased future risk of type 2 diabetes and should prompt long-term follow-up and prevention advice."
    }
  ]
};
