window.quizBanks = window.quizBanks || {};
window.quizBanks.elc4 = {
  id: "elc4",
  title: "ELC4 — Pregnancy, placenta, labour and neonates",
  shortTitle: "ELC4",
  description: "Placental development, fetal growth, maternal adaptation, labour, postpartum haemorrhage, neonatal transition and prematurity.",
  blueprintBatch: "Batch D",
  questions: [
    {
      id: "pregnancy-spiral-artery-remodelling-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Placenta and fetal growth",
      component: "Spiral artery remodelling and placental perfusion",
      moduleLOs: ["LO1", "LO2"],
      sessionLOs: ["Describe placental development and structure and how this influences function", "Describe how the placenta mediates transport of nutrients to support fetal growth and what may disturb it"],
      disciplines: ["embryology", "physiology", "pathology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "mechanism",
      variantType: "placental-pathophysiology",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review trophoblast invasion, spiral artery remodelling and how failed low-resistance placental perfusion links to pre-eclampsia and fetal growth restriction.",
      question: "A pregnant patient develops hypertension and fetal growth restriction. Placental pathology suggests poor conversion of maternal spiral arteries into low-resistance vessels.",
      leadIn: "Which process has most likely failed?",
      options: ["Trophoblast-mediated spiral artery remodelling", "Closure of the ductus arteriosus", "Capacitation of sperm in the female reproductive tract", "Corpus luteum regression after fertilisation", "Peripheral deiodination of T4 to T3"],
      answer: 0,
      explanation: "Trophoblast invasion normally remodels spiral arteries into low-resistance vessels. Failure is associated with pre-eclampsia and fetal growth restriction."
    },
    {
      id: "placenta-syncytiotrophoblast-function-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Placenta and fetal growth",
      component: "Placental structure and syncytiotrophoblast function",
      moduleLOs: ["LO1", "LO2"],
      sessionLOs: ["Describe placental development and structure and how this influences function"],
      disciplines: ["embryology", "physiology"],
      cognitiveLevel: "understand",
      assessmentSkill: "function",
      variantType: "placental-structure-function",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review the syncytiotrophoblast as the placental layer in contact with maternal blood, involved in transport and hormone production.",
      question: "A diagram of a chorionic villus shows the outer trophoblast layer directly exposed to maternal blood in the intervillous space.",
      leadIn: "Which function is most associated with this layer?",
      options: ["Maternal-fetal exchange and placental hormone production", "Formation of fetal red blood cells only", "Contraction of uterine smooth muscle", "Production of fetal surfactant", "Closure of the foramen ovale"],
      answer: 0,
      explanation: "The syncytiotrophoblast is in contact with maternal blood and is central to placental exchange and hormone production such as hCG and hPL."
    },
    {
      id: "placenta-glucose-transport-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Placenta and fetal growth",
      component: "Placental nutrient transport mechanisms",
      moduleLOs: ["LO1", "LO2", "LO11"],
      sessionLOs: ["Describe how the placenta mediates transport of nutrients to support fetal growth and what may disturb it"],
      disciplines: ["physiology", "nutrition"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "placental-transport",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review placental transport: gases by passive diffusion, glucose by facilitated diffusion via GLUT1, amino acids by active transport and IgG by endocytosis.",
      question: "A teaching diagram asks how glucose normally crosses the placenta to support fetal growth.",
      leadIn: "Which transport mechanism is most appropriate?",
      options: ["Facilitated diffusion via GLUT transporters", "Endocytosis like maternal IgG", "Sodium-driven active amino acid transport", "Aquaporin-2 insertion", "Cortical reaction after fertilisation"],
      answer: 0,
      explanation: "Glucose crosses the placenta mainly by facilitated diffusion via GLUT1 transporters. Maternal IgG crosses by endocytosis, especially in the third trimester."
    },
    {
      id: "fetal-growth-measurement-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Fetal growth",
      component: "Normal fetal growth measurement",
      moduleLOs: ["LO1", "LO2", "LO6"],
      sessionLOs: ["Describe normal fetal growth, the factors that influence it and how we measure it"],
      disciplines: ["obstetrics", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "growth-monitoring",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review fetal growth assessment using symphysis-fundal height from around 24 weeks and serial ultrasound biometry when indicated.",
      question: "A pregnant patient at 28 weeks has a symphysis-fundal height lower than expected for gestation.",
      leadIn: "Which investigation is most appropriate to assess fetal growth more accurately?",
      options: ["Serial ultrasound biometry", "Maternal serum prolactin", "Day 5 heel-prick screening", "Dexamethasone suppression test", "Cervical cytology"],
      answer: 0,
      explanation: "Serial ultrasound biometry using measurements such as head circumference, abdominal circumference and femur length is used to assess fetal growth."
    },
    {
      id: "fgr-iugr-vs-sga-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Fetal growth",
      component: "SGA versus IUGR/FGR distinction",
      moduleLOs: ["LO9"],
      sessionLOs: ["Appreciate the clinical problems related to restricted or accelerated fetal growth"],
      disciplines: ["obstetrics", "pathology"],
      cognitiveLevel: "understand",
      assessmentSkill: "definition-discrimination",
      variantType: "growth-classification",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review that SGA can be constitutionally small and healthy, whereas IUGR/FGR implies pathological failure to reach growth potential.",
      question: "A baby is below the 10th centile but has normal Dopplers and no evidence of placental disease. The team distinguishes this from pathological growth restriction.",
      leadIn: "Which statement best describes this distinction?",
      options: ["SGA can be constitutionally small, whereas IUGR implies pathology", "SGA and IUGR always mean the same thing", "IUGR only describes accelerated fetal growth", "SGA requires immediate delivery in all cases", "IUGR is defined by maternal height alone"],
      answer: 0,
      explanation: "SGA means small for gestational age and may be constitutional. IUGR/FGR implies pathological restriction of growth potential."
    },
    {
      id: "fgr-doppler-progression-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Fetal growth",
      component: "Umbilical artery Doppler interpretation in FGR",
      moduleLOs: ["LO9", "LO13"],
      sessionLOs: ["Appreciate the clinical problems related to restricted fetal growth"],
      disciplines: ["obstetrics", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "doppler-interpretation",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review Doppler progression in FGR: normal, reduced, absent, then reversed end-diastolic flow; reversed flow suggests imminent stillbirth risk and need to deliver.",
      question: "A fetus with growth restriction has umbilical artery Doppler showing reversed end-diastolic flow.",
      leadIn: "Which interpretation is most appropriate?",
      options: ["Severe placental insufficiency with urgent delivery consideration", "A normal physiological finding in late pregnancy", "Evidence of fetal macrosomia", "A marker of maternal hyperthyroidism only", "Proof that the fetus is constitutionally small"],
      answer: 0,
      explanation: "Reversed end-diastolic flow is the severe end of Doppler abnormality in FGR and indicates high stillbirth risk, usually requiring delivery planning."
    },
    {
      id: "macrosomia-gdm-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Fetal growth",
      component: "Macrosomia and gestational diabetes consequences",
      moduleLOs: ["LO9"],
      sessionLOs: ["Appreciate the clinical problems related to accelerated fetal growth"],
      disciplines: ["obstetrics", "endocrinology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "macrosomia-complications",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review macrosomia risk in GDM and maternal obesity, including shoulder dystocia, birth injury and neonatal hypoglycaemia.",
      question: "A patient with gestational diabetes gives birth to a macrosomic baby. Soon after delivery the baby becomes jittery and has low blood glucose.",
      leadIn: "Which mechanism best explains the neonatal hypoglycaemia?",
      options: ["Persistent fetal hyperinsulinaemia after maternal glucose supply is removed", "Failure of maternal IgG transfer", "Low fetal thyroid hormone from iodine deficiency", "Closure of the ductus arteriosus by prostaglandin E", "Reduced fetal insulin secretion throughout pregnancy"],
      answer: 0,
      explanation: "In maternal diabetes, fetal hyperglycaemia drives fetal hyperinsulinaemia. After delivery the maternal glucose supply stops, but insulin remains high, causing hypoglycaemia."
    },
    {
      id: "pregnancy-physiological-anaemia-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Maternal adaptations",
      component: "Physiological anaemia of pregnancy",
      moduleLOs: ["LO2"],
      sessionLOs: ["Describe maternal metabolic, respiratory and cardiovascular adaptations to pregnancy"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "maternal-adaptation",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review that plasma volume rises more than red cell mass in pregnancy, causing dilutional physiological anaemia.",
      question: "A pregnant patient has a lower haemoglobin concentration despite an increase in total red cell mass.",
      leadIn: "Which physiological change best explains this finding?",
      options: ["Plasma volume increases more than red cell mass", "Systemic vascular resistance rises sharply", "GFR falls throughout pregnancy", "Tidal volume decreases", "Placental hPL reduces insulin resistance"],
      answer: 0,
      explanation: "Pregnancy increases plasma volume by around 40%, while red cell mass rises less. This dilution produces physiological anaemia of pregnancy."
    },
    {
      id: "pregnancy-respiratory-alkalosis-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Maternal adaptations",
      component: "Respiratory adaptation in pregnancy",
      moduleLOs: ["LO2"],
      sessionLOs: ["Explain major changes to the respiratory system that occur in pregnancy"],
      disciplines: ["physiology"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "maternal-respiratory-adaptation",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review pregnancy respiratory adaptation: progesterone increases tidal volume, producing mild respiratory alkalosis.",
      question: "A healthy pregnant patient has a mild respiratory alkalosis on blood gas analysis.",
      leadIn: "Which physiological change most likely explains this?",
      options: ["Increased tidal volume driven by progesterone", "Reduced oxygen demand", "Closure of the fetal ductus arteriosus", "Reduced maternal minute ventilation", "Suppressed placental CRH"],
      answer: 0,
      explanation: "Progesterone increases ventilation, particularly tidal volume, causing mild respiratory alkalosis during pregnancy."
    },
    {
      id: "pregnancy-vte-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Maternal adaptations",
      component: "Coagulation adaptation in pregnancy",
      moduleLOs: ["LO2", "LO9"],
      sessionLOs: ["Explain major changes to the cardiovascular and coagulation systems in pregnancy"],
      disciplines: ["physiology", "clinical aspects"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "maternal-coagulation-adaptation",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review pregnancy as a procoagulant state that increases VTE risk.",
      question: "A pregnant patient is assessed for calf swelling and pleuritic chest pain. The clinician notes pregnancy itself increases thrombotic risk.",
      leadIn: "Which physiological adaptation explains this increased risk?",
      options: ["A procoagulant state", "Reduced plasma volume", "Reduced cardiac output", "Reduced renal clearance", "Low placental hormone production"],
      answer: 0,
      explanation: "Pregnancy is a procoagulant state, increasing the risk of venous thromboembolism."
    },
    {
      id: "pregnancy-stress-test-pet-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Maternal adaptations",
      component: "Pregnancy as a stress test for future health",
      moduleLOs: ["LO2", "LO8"],
      sessionLOs: ["Explain the concept of pregnancy as a stress test for future health"],
      disciplines: ["public health", "clinical aspects"],
      cognitiveLevel: "understand",
      assessmentSkill: "integration",
      variantType: "future-health-risk",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review pregnancy as a stress test: GDM predicts future T2DM, and pre-eclampsia predicts future cardiovascular disease risk.",
      question: "A patient had pre-eclampsia in her first pregnancy and asks why her GP has recommended future cardiovascular risk review.",
      leadIn: "Which explanation is most appropriate?",
      options: ["Pre-eclampsia is associated with increased future cardiovascular disease risk", "Pre-eclampsia protects against later hypertension", "Only gestational diabetes predicts future disease", "Pre-eclampsia is unrelated to vascular health", "Future risk assessment is only needed after stillbirth"],
      answer: 0,
      explanation: "Pregnancy can reveal underlying vascular or metabolic vulnerability. Pre-eclampsia is associated with increased future cardiovascular disease risk."
    },
    {
      id: "labour-stages-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour",
      component: "Stages of labour",
      moduleLOs: ["LO1", "LO2"],
      sessionLOs: ["Describe the process of labour"],
      disciplines: ["obstetrics"],
      cognitiveLevel: "remember",
      assessmentSkill: "developmental-timing",
      variantType: "labour-stages",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review the three stages of labour: cervical dilatation to 10 cm, delivery of the baby, then placental delivery.",
      question: "A patient in labour has reached full cervical dilatation and is beginning active pushing.",
      leadIn: "Which stage of labour is this?",
      options: ["Second stage", "First stage", "Third stage", "Latent pre-labour only", "Puerperium"],
      answer: 0,
      explanation: "The second stage runs from full cervical dilatation to delivery of the baby. The first stage is cervical effacement and dilatation to 10 cm."
    },
    {
      id: "labour-oxytocin-mechanism-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour",
      component: "Oxytocin mechanism in uterine contraction",
      moduleLOs: ["LO1", "LO2"],
      sessionLOs: ["Describe mechanisms controlling uterine activity"],
      disciplines: ["physiology", "pharmacology"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "labour-uterine-contraction",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review oxytocin as acting through Gq signalling to increase intracellular calcium and contract uterine smooth muscle.",
      question: "Oxytocin is used to stimulate uterine contractions.",
      leadIn: "Which intracellular change directly promotes contraction?",
      options: ["Increased intracellular calcium", "Reduced prostaglandin receptor expression", "Closure of fetal shunts", "Suppression of myometrial Gq signalling", "Reduced cervical stretch feedback"],
      answer: 0,
      explanation: "Oxytocin acts via Gq signalling, increasing intracellular calcium and causing uterine smooth muscle contraction."
    },
    {
      id: "labour-ferguson-reflex-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour",
      component: "Ferguson reflex and positive feedback",
      moduleLOs: ["LO1", "LO2"],
      sessionLOs: ["Describe mechanisms controlling uterine activity"],
      disciplines: ["physiology", "obstetrics"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "positive-feedback",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review the Ferguson reflex: cervical stretch increases oxytocin release, causing more uterine contraction and more stretch.",
      question: "During labour, cervical stretch increases oxytocin release, which increases uterine contractions and further cervical stretch.",
      leadIn: "Which feedback pattern does this describe?",
      options: ["Positive feedback", "Negative feedback", "Osmotic feedback", "Portal vessel inhibition", "Renin-angiotensin feedback"],
      answer: 0,
      explanation: "The Ferguson reflex is a positive feedback loop because the response amplifies the initial stimulus."
    },
    {
      id: "labour-entonoxtiming-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour pharmacology",
      component: "Pain relief in labour",
      moduleLOs: ["LO7"],
      sessionLOs: ["Describe the pharmacology of pain relief during labour"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "labour-analgesia",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review labour analgesia: Entonox is short acting with no neonatal effect; opioids near delivery may cause neonatal respiratory depression; epidural can increase instrumental delivery risk.",
      question: "A patient in labour wants short-acting analgesia that she can control herself and that has no neonatal respiratory depressant effect.",
      leadIn: "Which option best fits this request?",
      options: ["Entonox", "Intramuscular pethidine immediately before birth", "Carboprost", "Mifepristone", "Ergometrine"],
      answer: 0,
      explanation: "Entonox is short acting and has no neonatal respiratory depressant effect. Opioids close to delivery can depress neonatal respiration."
    },
    {
      id: "pph-oxytocin-firstline-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour pharmacology",
      component: "Post-partum haemorrhage first-line uterotonic",
      moduleLOs: ["LO7", "LO9"],
      sessionLOs: ["Describe pharmacological regulation of post-partum haemorrhage"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "pph-management",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review oxytocin as the first-line uterotonic for PPH because it causes uterine contraction via Gq calcium signalling.",
      question: "A patient has uterine atony with heavy bleeding after delivery. A first-line uterotonic is needed.",
      leadIn: "Which medication is most appropriate first line?",
      options: ["Oxytocin", "Methotrexate", "Cabergoline", "Warfarin", "Aciclovir"],
      answer: 0,
      explanation: "Oxytocin is first-line for uterine atony/PPH and causes uterine contraction."
    },
    {
      id: "pph-ergometrine-contraindication-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour pharmacology",
      component: "Ergometrine drug safety",
      moduleLOs: ["LO7"],
      sessionLOs: ["Describe pharmacological regulation of post-partum haemorrhage"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "pph-drug-safety",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review ergometrine as a uterotonic that should be avoided in hypertension, pre-eclampsia and cardiovascular disease because of vasoconstriction.",
      question: "A patient with severe pre-eclampsia has post-partum haemorrhage. The team avoids a vasoconstricting uterotonic.",
      leadIn: "Which drug is being avoided because of the hypertension risk?",
      options: ["Ergometrine", "Oxytocin", "Tranexamic acid", "Misoprostol", "Mifepristone"],
      answer: 0,
      explanation: "Ergometrine is a uterotonic but causes vasoconstriction and should be avoided in hypertension, pre-eclampsia and cardiovascular disease."
    },
    {
      id: "pph-carboprost-asthma-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour pharmacology",
      component: "Carboprost drug safety",
      moduleLOs: ["LO7"],
      sessionLOs: ["Describe pharmacological regulation of post-partum haemorrhage"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "pph-drug-safety",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review carboprost as PGF2alpha for severe PPH and avoid it in asthma.",
      question: "A patient with severe asthma develops post-partum haemorrhage. The team avoids a prostaglandin F2 alpha uterotonic.",
      leadIn: "Which drug should be avoided?",
      options: ["Carboprost", "Oxytocin", "Tranexamic acid", "Entonox", "Misoprostol"],
      answer: 0,
      explanation: "Carboprost is PGF2alpha and is used for severe PPH, but it should be avoided in asthma."
    },
    {
      id: "abortion-mifepristone-misoprostol-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Labour pharmacology",
      component: "Medical induction of abortion",
      moduleLOs: ["LO7"],
      sessionLOs: ["Describe induction of abortion pharmacology"],
      disciplines: ["pharmacology", "reproductive health"],
      cognitiveLevel: "understand",
      assessmentSkill: "management",
      variantType: "abortion-pharmacology",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review medical abortion regimen: mifepristone, a progesterone receptor antagonist, followed by misoprostol.",
      question: "A medical abortion regimen is planned using mifepristone followed by misoprostol.",
      leadIn: "What is the main action of mifepristone?",
      options: ["Progesterone receptor antagonism", "Dopamine receptor agonism", "Beta-lactam antibiotic activity", "Aquaporin-2 insertion", "HER2 receptor blockade"],
      answer: 0,
      explanation: "Mifepristone is a progesterone receptor antagonist. It is followed by misoprostol, a prostaglandin analogue."
    },
    {
      id: "neonatal-surfactant-rds-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Neonatal transition",
      component: "Surfactant maturity and respiratory distress syndrome",
      moduleLOs: ["LO2", "LO9"],
      sessionLOs: ["Describe how the fetus must be sufficiently mature to survive after birth"],
      disciplines: ["neonatal physiology", "pathology"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "neonatal-rds",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review surfactant production by type II pneumocytes maturing around 34–36 weeks; deficiency in preterm infants causes RDS.",
      question: "A baby born at 28 weeks develops respiratory distress shortly after birth due to alveolar collapse.",
      leadIn: "Which deficiency is the most likely cause?",
      options: ["Surfactant deficiency", "Excess maternal IgG transfer", "High fetal brown fat stores", "Persistent maternal glucose supply", "Premature closure of the foramen ovale before labour"],
      answer: 0,
      explanation: "Preterm babies are at risk of surfactant deficiency because surfactant matures later in gestation, around 34–36 weeks. Deficiency causes respiratory distress syndrome."
    },
    {
      id: "neonatal-circulation-transition-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Neonatal transition",
      component: "Fetal to neonatal circulatory transition",
      moduleLOs: ["LO2"],
      sessionLOs: ["Describe physiological adaptations for successful transition from fetal to neonatal life"],
      disciplines: ["physiology", "neonatal"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "neonatal-circulation",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review the first breath: pulmonary vascular resistance falls, left atrial pressure rises and the foramen ovale closes; rising oxygen and falling prostaglandins close the ductus arteriosus.",
      question: "A newborn takes their first breaths and pulmonary vascular resistance falls.",
      leadIn: "Which pressure change helps close the foramen ovale?",
      options: ["Left atrial pressure becomes higher than right atrial pressure", "Right atrial pressure becomes higher than left atrial pressure", "Umbilical venous pressure rises", "Pulmonary vascular resistance rises", "Placental resistance falls"],
      answer: 0,
      explanation: "After lung aeration, pulmonary blood flow increases, left atrial pressure rises and exceeds right atrial pressure, functionally closing the foramen ovale."
    },
    {
      id: "pda-indomethacin-pge-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Neonatal transition",
      component: "Ductus arteriosus pharmacology",
      moduleLOs: ["LO2", "LO7"],
      sessionLOs: ["Describe physiological adaptations for successful transition from fetal to neonatal life"],
      disciplines: ["physiology", "pharmacology", "neonatal"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "ductus-pharmacology",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review ductus arteriosus pharmacology: indomethacin closes a PDA; prostaglandin E keeps it open in duct-dependent congenital heart disease.",
      question: "A neonate has a patent ductus arteriosus that needs pharmacological closure.",
      leadIn: "Which drug promotes ductal closure?",
      options: ["Indomethacin", "Prostaglandin E", "Magnesium sulphate", "Betamethasone", "Ergometrine"],
      answer: 0,
      explanation: "Indomethacin inhibits prostaglandin production and can close a PDA. Prostaglandin E keeps the duct open in duct-dependent congenital heart disease."
    },
    {
      id: "neonatal-hypoglycaemia-diabetic-mother-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Neonatal transition",
      component: "Neonatal glucose adaptation",
      moduleLOs: ["LO2", "LO9"],
      sessionLOs: ["Consider pathological situations where normal adaptations cannot take place"],
      disciplines: ["neonatal", "endocrinology"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "neonatal-glucose",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review that babies of diabetic mothers are at risk of hypoglycaemia because fetal hyperinsulinaemia persists after the maternal glucose supply stops.",
      question: "A baby of a mother with diabetes becomes jittery two hours after birth and has low capillary glucose.",
      leadIn: "Which mechanism best explains this?",
      options: ["Residual fetal hyperinsulinaemia after delivery", "Absence of placental IgG transfer", "Excess brown fat thermogenesis", "Closed ductus arteriosus from prostaglandin E", "Maternal anaemia of pregnancy"],
      answer: 0,
      explanation: "Maternal hyperglycaemia drives fetal insulin secretion. After birth the maternal glucose supply ends but fetal insulin remains high, causing hypoglycaemia."
    },
    {
      id: "preterm-definition-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Preterm labour",
      component: "Definition of preterm birth",
      moduleLOs: ["LO9"],
      sessionLOs: ["Understand relevant definitions relating to preterm labour and birth"],
      disciplines: ["obstetrics"],
      cognitiveLevel: "remember",
      assessmentSkill: "definition-discrimination",
      variantType: "preterm-definition",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review preterm birth as birth before 37 completed weeks, with extremely preterm under 28 weeks.",
      question: "A baby is born at 35+2 weeks' gestation.",
      leadIn: "Which category best describes this birth?",
      options: ["Preterm", "Post-term", "Extremely preterm", "Term", "Miscarriage by definition"],
      answer: 0,
      explanation: "Preterm birth is birth before 37 weeks. A birth at 35+2 weeks is preterm, more specifically late preterm."
    },
    {
      id: "preterm-predictors-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Preterm labour",
      component: "Predictors of preterm birth",
      moduleLOs: ["LO9", "LO13"],
      sessionLOs: ["Appreciate risks and predictors of early birth"],
      disciplines: ["obstetrics", "clinical aspects"],
      cognitiveLevel: "analyse",
      assessmentSkill: "data-interpretation",
      variantType: "preterm-risk-prediction",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review preterm birth predictors: previous preterm birth, cervical length under 25 mm on TVUS and positive fetal fibronectin.",
      question: "A pregnant patient has previous spontaneous preterm birth. Transvaginal ultrasound shows cervical length of 18 mm.",
      leadIn: "Which interpretation is most appropriate?",
      options: ["Increased risk of preterm birth", "Reassuring normal cervical length", "Diagnostic of fetal macrosomia", "Evidence of neonatal hypoglycaemia", "Definition of post-term pregnancy"],
      answer: 0,
      explanation: "A short cervix, often under 25 mm on transvaginal ultrasound, is a predictor of preterm birth, especially with previous preterm birth."
    },
    {
      id: "preterm-steroids-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Preterm labour",
      component: "Antenatal corticosteroids for fetal lung maturity",
      moduleLOs: ["LO7", "LO9"],
      sessionLOs: ["Discuss risk benefits and principles of treatment and interventions in preterm labour"],
      disciplines: ["pharmacology", "obstetrics", "neonatal"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "preterm-treatment",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review antenatal corticosteroids, such as betamethasone or dexamethasone, given at 24–34 weeks to accelerate fetal surfactant production.",
      question: "A patient at 29 weeks is in threatened preterm labour. The fetus is likely to be delivered within the next week.",
      leadIn: "Which intervention is used to accelerate fetal lung maturation?",
      options: ["Antenatal corticosteroids", "Ergometrine", "Cabergoline", "Warfarin", "Copper IUD"],
      answer: 0,
      explanation: "Antenatal corticosteroids between 24 and 34 weeks accelerate fetal surfactant production and reduce neonatal respiratory morbidity."
    },
    {
      id: "preterm-magnesium-neuroprotection-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Preterm labour",
      component: "Magnesium sulphate neuroprotection",
      moduleLOs: ["LO7", "LO9"],
      sessionLOs: ["Discuss risk benefits and principles of treatment and interventions in preterm labour"],
      disciplines: ["pharmacology", "obstetrics", "neonatal"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "preterm-neuroprotection",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review magnesium sulphate before 30 weeks for fetal neuroprotection and reduced cerebral palsy risk.",
      question: "A patient at 28 weeks is expected to deliver imminently. The team gives magnesium sulphate before birth.",
      leadIn: "What is the main fetal benefit?",
      options: ["Neuroprotection with reduced cerebral palsy risk", "Immediate ductus arteriosus closure", "Treatment of maternal chlamydia", "Induction of medical abortion", "Prevention of endometrial cancer"],
      answer: 0,
      explanation: "Magnesium sulphate given before very preterm birth, particularly before 30 weeks, provides fetal neuroprotection and reduces cerebral palsy risk."
    },
    {
      id: "preterm-tocolysis-purpose-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Preterm labour",
      component: "Purpose of tocolysis",
      moduleLOs: ["LO7", "LO9"],
      sessionLOs: ["Discuss risk benefits and principles of treatment and interventions in preterm labour"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "understand",
      assessmentSkill: "management",
      variantType: "preterm-treatment-principle",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review tocolysis as short-term delay of preterm birth to allow antenatal steroids and in-utero transfer, not as a cure for preterm labour.",
      question: "A patient in preterm labour is given nifedipine as a tocolytic.",
      leadIn: "What is the main purpose of this intervention?",
      options: ["To buy time for steroids and in-utero transfer", "To permanently prevent labour until term", "To close the fetal ductus arteriosus", "To treat fetal hypoglycaemia", "To increase cervical dilatation"],
      answer: 0,
      explanation: "Tocolysis can delay labour briefly, allowing antenatal corticosteroids and transfer to a centre with appropriate neonatal care."
    },
    {
      id: "preterm-pprom-antibiotics-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Preterm labour",
      component: "PPROM management principle",
      moduleLOs: ["LO7", "LO9"],
      sessionLOs: ["Discuss risk benefits and principles of treatment and interventions in preterm labour"],
      disciplines: ["obstetrics", "infection", "pharmacology"],
      cognitiveLevel: "apply",
      assessmentSkill: "management",
      variantType: "pprom-management",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review PPROM as preterm prelabour rupture of membranes and the role of antibiotics because infection risk is increased.",
      question: "A patient at 31 weeks has preterm prelabour rupture of membranes and no signs of immediate delivery.",
      leadIn: "Which treatment principle is particularly relevant because of infection risk?",
      options: ["Give antibiotics", "Avoid all fetal monitoring", "Give mifepristone first line", "Start ergometrine immediately", "Perform cervical cytology as treatment"],
      answer: 0,
      explanation: "PPROM increases infection risk, so antibiotics are used as part of management when appropriate."
    },
    {
      id: "prematurity-consequences-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Prematurity",
      component: "Neonatal consequences of prematurity",
      moduleLOs: ["LO9"],
      sessionLOs: ["Discuss the neonatal consequences of prematurity"],
      disciplines: ["neonatal", "pathology"],
      cognitiveLevel: "apply",
      assessmentSkill: "clinical-recognition",
      variantType: "prematurity-complications",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review complications of prematurity: RDS, IVH, NEC, sepsis, ROP, BPD, hypothermia, hypoglycaemia, jaundice and long-term neurodevelopmental impact.",
      question: "A very preterm baby develops feeding intolerance, abdominal distension and systemic instability. Necrotising enterocolitis is suspected.",
      leadIn: "Which broader category does this complication belong to?",
      options: ["Neonatal consequence of prematurity", "Expected feature of post-term birth", "Typical sign of maternal menopause", "Diagnostic criterion for PCOS", "Normal placental transport mechanism"],
      answer: 0,
      explanation: "Necrotising enterocolitis is one of the recognised neonatal complications of prematurity."
    },
    {
      id: "pregnancy-teratogen-critical-period-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Pregnancy drugs",
      component: "Teratogens and critical developmental timing",
      moduleLOs: ["LO7", "LO9", "LO11"],
      sessionLOs: ["Explain the term teratogenic and how this impacts fetal development"],
      disciplines: ["pharmacology", "embryology"],
      cognitiveLevel: "understand",
      assessmentSkill: "developmental-timing",
      variantType: "teratogen-timing",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review teratogen timing: 3–8 weeks is the critical organogenesis period for major structural malformations; earlier exposure is often all-or-nothing and later exposure more functional.",
      question: "A teratogenic drug is taken during embryonic organogenesis.",
      leadIn: "Which gestational period is most associated with major structural malformation risk?",
      options: ["3–8 weeks", "34–36 weeks", "After birth only", "After menopause", "Day 5 neonatal screening"],
      answer: 0,
      explanation: "The critical period for major structural malformations is organogenesis, approximately weeks 3–8."
    },
    {
      id: "pregnancy-acei-arb-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Pregnancy drugs",
      component: "Prescription drugs of concern in pregnancy",
      moduleLOs: ["LO7", "LO11"],
      sessionLOs: ["Describe major prescription drug classes of concern in pregnancy"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "pregnancy-prescribing-safety",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review drugs to avoid in pregnancy: ACE inhibitors and ARBs can cause fetal renal damage and skull defects.",
      question: "A patient taking an ACE inhibitor for hypertension becomes pregnant and asks why it should be changed.",
      leadIn: "Which fetal risk is most associated with this drug class?",
      options: ["Renal damage and skull defects", "Improved fetal lung surfactant production", "Reduced neural tube defect risk", "Protection against neonatal hypoglycaemia", "Prevention of fetal teeth discolouration"],
      answer: 0,
      explanation: "ACE inhibitors and ARBs should be avoided in pregnancy because they can cause fetal renal damage and skull defects."
    },
    {
      id: "pregnancy-valproate-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Pregnancy drugs",
      component: "Sodium valproate teratogenicity",
      moduleLOs: ["LO7", "LO9", "LO11"],
      sessionLOs: ["Describe major prescription drug classes of concern in pregnancy"],
      disciplines: ["pharmacology", "embryology"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "pregnancy-teratogen",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review sodium valproate as a high-risk teratogen associated with neural tube defects and fetal valproate syndrome.",
      question: "A patient with epilepsy is planning pregnancy. Medication review identifies sodium valproate as a concern.",
      leadIn: "Which fetal risk is classically associated with sodium valproate?",
      options: ["Neural tube defects and fetal valproate syndrome", "Fetal teeth discolouration only", "Premature ductus arteriosus closure only", "Congenital hypothyroidism from iodine deficiency", "Transient neonatal prolactin deficiency"],
      answer: 0,
      explanation: "Sodium valproate is associated with neural tube defects and fetal valproate syndrome. It requires careful specialist review before pregnancy."
    },
    {
      id: "pregnancy-nsaid-late-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Pregnancy drugs",
      component: "Late pregnancy NSAID risk",
      moduleLOs: ["LO7", "LO11"],
      sessionLOs: ["Describe major prescription drug classes of concern in pregnancy"],
      disciplines: ["pharmacology", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "pregnancy-prescribing-safety",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review that NSAIDs late in pregnancy can close the fetal ductus arteriosus and cause oligohydramnios.",
      question: "A patient in the third trimester asks whether regular NSAID use is safe.",
      leadIn: "Which fetal complication is a key concern with late NSAID exposure?",
      options: ["Premature ductus arteriosus closure", "Delayed closure of the foramen ovale only", "Increased maternal IgG transfer", "Fetal hyperinsulinaemia prevention", "Reduced risk of oligohydramnios"],
      answer: 0,
      explanation: "NSAIDs late in pregnancy can cause premature closure of the fetal ductus arteriosus and oligohydramnios."
    },
    {
      id: "pregnancy-smoking-risk-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Pregnancy drugs and substances",
      component: "Smoking risks in pregnancy",
      moduleLOs: ["LO7", "LO11"],
      sessionLOs: ["Explain why smoking, drinking and illicit drug use should be avoided in pregnancy"],
      disciplines: ["public health", "obstetrics"],
      cognitiveLevel: "apply",
      assessmentSkill: "psychosocial-communication",
      variantType: "pregnancy-substance-risk",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review smoking in pregnancy as linked to IUGR, preterm birth, placental abruption and SIDS.",
      question: "A pregnant patient who smokes asks how smoking can affect the pregnancy.",
      leadIn: "Which risk is most directly associated with smoking in pregnancy?",
      options: ["Fetal growth restriction", "Protection against preterm birth", "Reduced placental abruption risk", "Guaranteed fetal macrosomia", "Prevention of SIDS"],
      answer: 0,
      explanation: "Smoking in pregnancy is associated with fetal growth restriction, preterm birth, placental abruption and SIDS risk."
    },
    {
      id: "pregnancy-igG-transfer-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Immunology of pregnancy",
      component: "Maternal IgG transfer",
      moduleLOs: ["LO2"],
      sessionLOs: ["Understand how maternal immunity offers protection of the infant"],
      disciplines: ["immunology", "neonatal"],
      cognitiveLevel: "understand",
      assessmentSkill: "mechanism",
      variantType: "maternal-immunity",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review maternal IgG transfer mainly in the third trimester and breast milk IgA as mucosal protection after birth.",
      question: "A very preterm baby is more susceptible to infection partly because less maternal antibody crossed the placenta before birth.",
      leadIn: "Which antibody is transferred across the placenta mainly in the third trimester?",
      options: ["IgG", "IgA", "IgM", "IgE", "IgD"],
      answer: 0,
      explanation: "Maternal IgG crosses the placenta, especially in the third trimester. Preterm infants receive less placental IgG transfer."
    },
    {
      id: "pregnancy-vaccination-live-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Immunology of pregnancy",
      component: "Vaccination in pregnancy",
      moduleLOs: ["LO2", "LO14"],
      sessionLOs: ["Discuss how maternal immunity is enhanced by vaccination in pregnancy"],
      disciplines: ["immunology", "public health"],
      cognitiveLevel: "apply",
      assessmentSkill: "drug-safety",
      variantType: "pregnancy-vaccination",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review vaccination in pregnancy: pertussis, influenza and COVID vaccines are recommended; live vaccines such as MMR and varicella are contraindicated.",
      question: "A pregnant patient asks which vaccines are avoided during pregnancy because they are live vaccines.",
      leadIn: "Which vaccine should generally be avoided during pregnancy?",
      options: ["MMR", "Pertussis", "Influenza", "COVID vaccine", "Inactivated influenza vaccine"],
      answer: 0,
      explanation: "Live vaccines such as MMR and varicella are generally contraindicated in pregnancy. Pertussis and influenza vaccination are recommended."
    },
    {
      id: "perinatal-mortality-definition-001",
      module: "ELC",
      paper: "Paper 2",
      topic: "Perinatal outcomes",
      component: "Perinatal mortality definition",
      moduleLOs: ["LO9", "LO14"],
      sessionLOs: ["Identify the concept of perinatal mortality"],
      disciplines: ["public health", "obstetrics", "neonatal"],
      cognitiveLevel: "remember",
      assessmentSkill: "definition-discrimination",
      variantType: "perinatal-mortality",
      questionType: "single-best-answer",
      status: "approved",
      revisionAction: "Review perinatal mortality as stillbirths plus early neonatal deaths.",
      question: "A public health report describes perinatal mortality rates.",
      leadIn: "Which events are included in this measure?",
      options: ["Stillbirths and early neonatal deaths", "All maternal deaths only", "Deaths from cancer in older adults", "Only deaths after the first birthday", "Miscarriages before viability only"],
      answer: 0,
      explanation: "Perinatal mortality includes stillbirths and early neonatal deaths."
    }
  ]
};
